on:
  push:
    tags:
      - 'v*'  # Trigger for tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')  # Ensure the tag starts with 'v' for SemVer validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          # Extract version from the tag
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=$(echo "$TAG_NAME" | grep -Eo '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo "invalid")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Ensure valid SemVer tag
        run: |
          if [[ "${{ env.VERSION }}" == "invalid" ]]; then
            echo "Error: Tag does not follow SemVer format. Exiting."
            exit 1
          fi
          echo "Valid SemVer tag: ${{ env.VERSION }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Set in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set in GitHub Secrets

      - name: Build new Docker image manually
        run: |
          # Use docker commit to create an image from a container (if needed, otherwise you can skip this)
          docker commit python-stats-app-tag python-stats-app-tag:latest

          # Tag the image manually
          docker tag python-stats-app-tag:latest ivaylorashkov/python-stats-app-tag:${{ env.VERSION }}  # Tag with version
          docker tag python-stats-app-tag:latest ivaylorashkov/python-stats-app-tag:latest  # Always update latest

      - name: Push new Docker image
        run: |
          docker push ivaylorashkov/python-stats-app-tag:${{ env.VERSION }}  # Push with version tag
          docker push ivaylorashkov/python-stats-app-tag:latest  # Always push latest tag