name: Build and Push Docker Image

on:
  pull_request:
    types:
      - labeled  # Triggers when a label is added
    branches:
      - master  # Only runs on PRs targeting `master`

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'SemVer')  # Run only if 'SemVer' label exists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Set this in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set this in GitHub Secrets

      - name: Build and push Docker image to Docker Hub Registry
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ivaylorashkov/python-stats-app:latest 
