name: Build and Push Docker Image ON PR

on:
  pull_request:
    types:
      - labeled  # Trigger when a label is added
    branches:
      - master  # Only run on PRs targeting master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract SemVer from Label
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.labels }}" | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "latest")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Check if SemVer label exists
        run: |
          if [[ "${{ env.VERSION }}" == "latest" ]]; then
            echo "No valid SemVer label found, exiting."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Set in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set in GitHub Secrets

      - name: Build and push Docker image to Docker Hub Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ivaylorashkov/python-stats-app-pr:${{ env.VERSION }}  # Use extracted SemVer
            ivaylorashkov/python-stats-app:latest  # Always update latest
