name: Build and Push Docker Image on Push

on:
  push:
    branches: ["master"]
    tags:
      - 'v*'  # This ensures the workflow triggers for tags following SemVer format, e.g., v1.0.0
    # Alternatively, you could use a label by using `pull_request` instead of `push` if that's required.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          # Extract version from the tag (without 'v' prefix)
          TAG_NAME=${GITHUB_REF##*/}  # This gets the tag name (e.g., v2.0.5)
          VERSION=$(echo "$TAG_NAME" | sed 's/^v//')  # Remove 'v' if needed (result will be 2.0.5)
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Set the VERSION environment variable
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Set this in your GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set this in your GitHub Secrets

      - name: Build and push Docker image to Docker Hub Registry
        uses: docker/build-push-action@v6
        with:
            context: ./pythonenv
            push: true
            tags: ivaylorashkov/python-stats-app-specific-tag:${{ env.VERSION }}

