name: Build and Push Docker Image on Tag Creation

on:
  push:
    tags:
      - 'v*'  # Trigger for tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')  # Ensure the tag starts with 'v' for SemVer validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          # Extract version from the tag
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=$(echo "$TAG_NAME" | grep -Eo '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo "invalid")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Ensure valid SemVer tag
        run: |
          if [[ "${{ env.VERSION }}" == "invalid" ]]; then
            echo "Error: Tag does not follow SemVer format. Exiting."
            exit 1
          fi
          echo "Valid SemVer tag: ${{ env.VERSION }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Set in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set in GitHub Secrets

      - name: Build and push Docker image to Docker Hub Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ivaylorashkov/python-stats-app:${{ env.VERSION }}  # This is the valid tag (no inline comment in tag)
            ivaylorashkov/python-stats-app:latest  # Always update latest
